replicaCount: 2

image:
  tag: "latest"

service:
  type: LoadBalancer
  port: 11130

ingress:
  hosts:
    - host: dev.app.tamedia.k8s-cluster.com
  tls:
      hosts:
        - dev.app.tamedia.k8s-cluster.com

resources:
   limits:
     cpu: 200m
     memory: 256Mi
   requests:
     cpu: 100m
     memory: 128Mi
